### ISSUE TITLE
Test API 报错

### ISSUE THREAD

**Issue by hatanoyui** [wangziyingwen/AutoApiSecret#40]
这是日志：
.
.
.2020-10-22T02:49:30.0315313Z ##[group]Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
2020-10-22T02:49:30.0315884Z [36;1mecho `date +"%Y-%m-%d %H:%M:%S"` begin > time.log[0m
2020-10-22T02:49:30.0316168Z [36;1mpython 2.py[0m
2020-10-22T02:49:30.0348768Z shell: /bin/bash -e {0}
2020-10-22T02:49:30.0348990Z env:
2020-10-22T02:49:30.0349332Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
2020-10-22T02:49:30.0349687Z ##[endgroup]
2020-10-22T02:49:30.0545636Z   File "2.py", line 13
2020-10-22T02:49:30.0546529Z     ***
2020-10-22T02:49:30.0546891Z                    ^
2020-10-22T02:49:30.0547136Z SyntaxError: invalid syntax
2020-10-22T02:49:30.0567037Z ##[error]Process completed with exit code 1.
2020-10-22T02:49:30.0638347Z Post job cleanup.
.
.
.

求解

**Comment by 67697** [comment]
![屏幕截图 2020-10-22 105740](https://user-images.githubusercontent.com/29675329/96819107-75704600-1455-11eb-9bc1-a65c54f84c49.png)

**Comment by fzsimlu** [comment]
Traceback (most recent call last):
  File "2.py", line 86, in <module>
    main()
  File "2.py", line 42, in main
    access_token=gettoken(refresh_token)
  File "2.py", line 31, in gettoken
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'

**Comment by fzsimlu** [comment]
有人遇到过？

**Comment by chris-ss** [comment]
> 这是日志：
> .
> .
> .2020-10-22T02:49:30.0315313Z ##[group]Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
> 2020-10-22T02:49:30.0315884Z �[36;1mecho `date +"%Y-%m-%d %H:%M:%S"` begin > time.log�[0m
> 2020-10-22T02:49:30.0316168Z �[36;1mpython 2.py�[0m
> 2020-10-22T02:49:30.0348768Z shell: /bin/bash -e {0}
> 2020-10-22T02:49:30.0348990Z env:
> 2020-10-22T02:49:30.0349332Z pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
> 2020-10-22T02:49:30.0349687Z ##[endgroup]
> 2020-10-22T02:49:30.0545636Z File "2.py", line 13
> 2020-10-22T02:49:30.0546529Z ***
> 2020-10-22T02:49:30.0546891Z ^
> 2020-10-22T02:49:30.0547136Z SyntaxError: invalid syntax
> 2020-10-22T02:49:30.0567037Z ##[error]Process completed with exit code 1.
> 2020-10-22T02:49:30.0638347Z Post job cleanup.
> .
> .
> .
> 
> 求解

和你一样的错误  解决了吗

**Comment by chris-ss** [comment]
解决了
看了下源代码13行是读取了id和key后报错格式问题
重新填了Setting里Secrets的id和key后问题解决
同样问题的检查一下自己的Id和key吧,注意单引号

CONFIG_ID
id=r'你的应用id'

CONFIG_KEY
secret=r'你的应用机密'

**Comment by hatanoyui** [comment]
### 今天重新填写了一遍 ID 和 应用机密，跑了一次居然可以了，待会看看autorun 怎么样
### 另外，我看到 你每天都在更新 refresh_token ，并且一天更新好几次，是为什么

**Comment by hatanoyui** [comment]
重新修改了 CONFIG_ID  CONFIG_KEY 就好了。
